CREATE TABLE T_FOLLOW (
    FOLLOWER_ID  NUMBER(15) NOT NULL,
    FOLLOWEE_ID  NUMBER(15) NOT NULL,
    FOLLOWED_AT  TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_FOLLOW PRIMARY KEY (FOLLOWER_ID, FOLLOWEE_ID),
    CONSTRAINT FK_T_FOLLOW_FOLLOWER FOREIGN KEY (FOLLOWER_ID)
        REFERENCES T_USER(USER_ID),
    CONSTRAINT FK_T_FOLLOW_FOLLOWEE FOREIGN KEY (FOLLOWEE_ID)
        REFERENCES T_USER(USER_ID)
);
