CREATE TABLE T_LIKE (
    USER_ID      NUMBER(15)    NOT NULL,
    TARGET_ID    NUMBER(15)    NOT NULL,
    TARGET_TYPE  NUMBER(1)     NOT NULL, -- 1: Tweet, 2: Comment
    LIKED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_LIKE PRIMARY KEY (USER_ID, TARGET_ID, TARGET_TYPE),
    CONSTRAINT FK_T_LIKE_USER FOREIGN KEY (USER_ID)
        REFERENCES T_USER(USER_ID)
);
