CREATE TABLE T_TWEET (
    TWEET_ID     NUMBER(15)       PRIMARY KEY,
    USER_ID      NUMBER(15)       NOT NULL,
    CONTENT      VARCHAR2(280 CHAR) NOT NULL,
    CREATED_AT   TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    IS_DELETED   NUMBER(1)         DEFAULT 0 NOT NULL,
    CONSTRAINT FK_T_TWEET_USER FOREIGN KEY (USER_ID)
        REFERENCES T_USER(USER_ID)
);
