CREATE TABLE T_USER (
    USER_ID       NUMBER(15)     PRIMARY KEY,
    NAME          VARCHAR2(50 CHAR) NOT NULL,
    EMAIL         VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    STATUS NUMBER(2) DEFAULT 0 NOT NULL
    CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    IS_DELETED    NUMBER(1)       DEFAULT 0 NOT NULL
);
